### ISSUE TITLE
Melhoria acentuação

### ISSUE THREAD

**Issue by admrodrigo2** [matheussn/Trabalho-IPC#1]
Permitir acentuações no código.
`printf("Numero invalido : %c",romano[i]);`

**Comment by hugonasciutti** [comment]
Problema resolvido no commit @4fe91fa58bd0e16060ec1e8b3a5960f690eab43a  e também consegui limitador no programa de 0 a 3999.

- [x] Corrigir problema de acentuação.
- [x] Colocar limitador de 0 a 3999.
