### ISSUE TITLE
Limitação de conversão

### ISSUE THREAD

**Issue by admrodrigo2** [matheussn/Trabalho-IPC#2]
O programa ainda não está limitando até 3999 na conversão de romanos para decimal. O de decimal para romano está ok.

**Comment by hugonasciutti** [comment]
Obrigado por reportar Rodrigo, o problema foi corrigido, por favor faça mais testes e continue encontrando erros e sugerindo melhorias. Re-abra este mesmo issue no botão abaixo caso o problema ainda não tenha sido resolvido.

- [x] Correção de leitura de romanos >3999.
