### ISSUE TITLE
Letras minusculas

### ISSUE THREAD

**Issue by admrodrigo2** [matheussn/Trabalho-IPC#3]
Verificar uma forma de transformar os caracteres romanos que o usuário digitar em maiúsculas. Tem uma função chamada toupper na biblioteca #include <ctype.h> que faz isso, mas não sei usar direito.

**Comment by hugonasciutti** [comment]
Obrigado pelo reporte, corrigi o problema sem utilizar esta biblioteca subtraindo 32 de cada char para torna-lo maiúsculo. Caso ainda esteja acontecendo o problema favor reabrir o caso.

- [x] Transformação de toda a String para maiúscula.

**Comment by hugonasciutti** [comment]
Resolução:
```
for(j=0; j<strlen(romano); j++){ // Transformando todas as letras em maiúsculas para comparação.
    if(romano[j] >= 97 && romano[j]<=122){
        romano[j] -= 32;
    }
```
